CREATE USER "Eliud" WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	REPLICATION
	CONNECTION LIMIT -1
	VALID UNTIL '2023-03-24T16:57:50+03:00' 
	PASSWORD 'Eliud&%45MtuStrong*4576*&@#';

GRANT postgres TO "Eliud";
COMMENT ON ROLE "Eliud" IS 'User for Capstone Image by DevCTraining';